### ISSUE TITLE
DateTime Picker

### ISSUE THREAD

**Issue by egadgetjnr** [maiconpinto/cakephp-adminlte-theme#10]
Hi There,
I'm having some difficulties and was wondering if you could suggest the best way to implement the Bootstrap DateTime Picker?

Thanks Heaps,

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/132617118856635/150045428990371)

**Comment by maiconpinto** [comment]
Implemented in https://github.com/maiconpinto/cakephp-adminlte-theme/commit/559bdb180d489dcf9fa93ceae7e0e5a616c7a7bd 

Now, I'll work in documentation about how to implement Datepicker.
