### ISSUE TITLE
Bake error on version 2.0.0

### ISSUE THREAD

**Issue by jranesio** [maiconpinto/cakephp-adminlte-theme#100]
PHP: 7.2
Cake: 4.0.3
Command: cake bake all table_name --theme AdminLTE

Error:
Exception: Unexpected token "name" of value "if" ("end of statement block" expected).
In [C:\xampp\htdocs\projetos\cake4admlte/vendor/maiconpinto/cakephp-adminlte-theme/templates\bake\Template\index.twig, line 63]

2020-03-29 11:50:59 Error: [Twig\Error\SyntaxError] Unexpected token "name" of value "if" ("end of statement block" expected). in C:\xampp\htdocs\projetos\cake4admlte/vendor/maiconpinto/cakephp-adminlte-theme/templates\bake\Template\index.twig on line 63
Stack Trace:
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\TokenParser\ForTokenParser.php:39
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Parser.php:182
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\TokenParser\IfTokenParser.php:39
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Parser.php:182
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\TokenParser\ForTokenParser.php:40
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Parser.php:182
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Parser.php:95
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Environment.php:479
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Environment.php:507
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Environment.php:348
- C:\xampp\htdocs\projetos\cake4admlte\vendor\twig\twig\src\Environment.php:309
- C:\xampp\htdocs\projetos\cake4admlte\vendor\wyrihaximus\twig-view\src\View\TwigView.php:192
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\bake\src\View\BakeView.php:114
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\bake\src\Utility\TemplateRenderer.php:101
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\bake\src\Command\TemplateCommand.php:386
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\bake\src\Command\TemplateCommand.php:137
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\bake\src\Command\AllCommand.php:94
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\cakephp\src\Console\BaseCommand.php:175
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\cakephp\src\Console\CommandRunner.php:336
- C:\xampp\htdocs\projetos\cake4admlte\vendor\cakephp\cakephp\src\Console\CommandRunner.php:171
- C:\xampp\htdocs\projetos\cake4admlte\bin\cake.php:12

**Comment by yarkm13** [comment]
@jranesio it's not related to bake itself, it's because new cake require most recent twig (in my setup it's v3.0.3 now) and twig greater than 1.4 deprecate conditions in loop definition.

I have created pull request for fix

**Comment by jranesio** [comment]
Thanks, solved
