### ISSUE TITLE
Adding an important USE in "Enable Theme" documentation section.

### ISSUE THREAD

**Issue by VARGA-Peter** [maiconpinto/cakephp-adminlte-theme#108]
I had the issue and according to the forum entries other beginners have it as well.

It would help/simplify to add the below line of code in the "Enable Theme" section in this page:
https://github.com/maiconpinto/cakephp-adminlte-theme

`use Cake\Event\EventInterface;`

**Comment by maiconpinto** [comment]
Thanks for your help, this fix available https://github.com/maiconpinto/cakephp-adminlte-theme/releases/tag/2.0.1
