### ISSUE TITLE
Deprecated Error: `element` tag is deprecated.

### ISSUE THREAD

**Issue by georgechitechi** [maiconpinto/cakephp-adminlte-theme#111]
While using bake command with --theme AdminLTE i get below error, this is Preventing "Add New" button from functioning.
Cakephp v 4.1.4
AdminLTE theme : 2.0.0

Other Themes are working fine

Deprecated Error: `element` tag is deprecated. Use `element()` function instead. - C:\xampp\htdocs\cakephp\vendor\twig\twig\src\Parser.php, line: 182
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php.
In [C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Core\functions.php, line 305]

Clicking "New" Outputs below Error.

![image](https://user-images.githubusercontent.com/52364198/94544282-19524180-025c-11eb-95ae-ac9604260cc7.png)

**Comment by maiconpinto** [comment]
https://github.com/maiconpinto/cakephp-adminlte-theme/releases/tag/2.0.1
