### ISSUE TITLE
Cannot install template

### ISSUE THREAD

**Issue by chetratep** [maiconpinto/cakephp-adminlte-theme#12]
Can you show step by step installation?
Try using composer already but nothing downloaded or installed !

**Comment by maiconpinto** [comment]
Hi @chetratep ,

You can update? Run `composer update`. 

If you can not to fix, let me know. 

I create other repository with app example: `github.com/maiconpinto/cakephp-app-adminlte-theme`

**Comment by maiconpinto** [comment]
Watch this video and let me know about your feedback.

https://www.youtube.com/watch?v=dGtLv8cq0vI
