### ISSUE TITLE
Form date options

### ISSUE THREAD

**Issue by elaros** [maiconpinto/cakephp-adminlte-theme#14]
The options minYear, maxYear and monthNames does not work in date/datetime input forms.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/132617118856635/174656780595933)

**Comment by feldmarv** [comment]
How to fix this issue? At the moment we just uncommented the function: protected function _datetimeOptions($options)

**Comment by maiconpinto** [comment]
Hello @feldmarv , keep calm, your issue will be done. If have you tip, feel yourself freedom to send PR.

**Comment by danielzzz** [comment]
any idea why it's happening? I tried to pin it down but haven't found anything...

**Comment by maiconpinto** [comment]
Hello, branch master has an update that fixes this error.

Soon I will create a new release.

**Comment by KasunWijesekara** [comment]
Any luck with the fix? The issue is still there in the current version of the build.
