### ISSUE TITLE
Cannot customize template

### ISSUE THREAD

**Issue by koffisani** [maiconpinto/cakephp-adminlte-theme#16]
It's a great template, but I'm facing issues when trying to customize it. I've created [`Element` files](https://github.com/maiconpinto/cakephp-adminlte-theme#customize-layout) but still can't see changes (an empty view is rendered).
NB : I've created `AdminController` in `Admin` folder for thos theme. 
Is there any recommendation ?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/132617118856635/195695560528448)

**Comment by maiconpinto** [comment]
Hi @koffisani you can see example custom footer in https://github.com/maiconpinto/cakephp-app-adminlte-theme/commit/a863ca529127566a4baf1002f37ab861416eaa3a and implemented in http://maiconpinto.com.br/cakephp-app-adminlte-theme

**Comment by maiconpinto** [comment]
Hi @koffisani!

Did you see my answer above? You could implement? 

Let me know if I can help you.

**Comment by koffisani** [comment]
Hi, @maiconpinto. Only `footer.ctp` and `dashboard.ctp` are rendered. 
As you can see on [this screeshot](https://github.com/koffisani/utils/blob/master/Panel%20d'Administration%20-%20mandealR%20-%20Google%20Chrome_003.png) (the footer is a little bit hidden).

**Comment by koffisani** [comment]
That's right now. Thanks.
