### ISSUE TITLE
Issue with password field

### ISSUE THREAD

**Issue by ajibarra** [maiconpinto/cakephp-adminlte-theme#17]
I have been checking issue with password field and it looks the code is duplicated from file field. If the code is removed the password fields are rendered correctly. Could you check please if the code is needed for anything?

[FormHelper::input() L104](https://github.com/maiconpinto/cakephp-adminlte-theme/blob/master/src/View/Helper/FormHelper.php#L104)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/132617118856635/196150682036833)

**Comment by maiconpinto** [comment]
Hi @ajibarra I removed it in https://github.com/maiconpinto/cakephp-adminlte-theme/commit/aa8ef6177583c7f95a29c507f6dd6f16fd9505b1

I will implement it in another moment.
