### ISSUE TITLE
Default.ctp

### ISSUE THREAD

**Issue by delamux** [maiconpinto/cakephp-adminlte-theme#23]
Hello, the file default.ctp, if i want to replace in my /src/template/layout doesn´t read in cake main directory.

only load from vendor directory.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/132617118856635/200552677317583)

**Comment by maiconpinto** [comment]
Hello @delamux what do you want to customize?

**Comment by maiconpinto** [comment]
@delamux you can set $this->viewBuilder()->theme(false) where you don't want to use _AdminLTE.Layout/default.ctp_.

**Comment by delamux** [comment]
Sorry @maiconpinto, i want to miedified the default.ctp, but if I create the condicional for create the default.ctp in my directory, and later if I need to update again the AdminLTE the conditional will go to disappear.

**Comment by maiconpinto** [comment]
You can create a new layout (`CTRL + C` of _default.ctp_ ) and use as you want.
