### ISSUE TITLE
Is there any Documentation about the FormHelper used?

### ISSUE THREAD

**Issue by feldmarv** [maiconpinto/cakephp-adminlte-theme#29]

**Comment by maiconpinto** [comment]
hello @feldmarv , I am sorry for so long time to wait the answer. The doc about FormHelper is not available yet. But, coming soon there will be.

**Comment by feldmarv** [comment]
thx because the theme is absolutely awesome including the bake templates!

**Comment by maiconpinto** [comment]
Thanks @feldmarv  follow the project to news
