### ISSUE TITLE
Unable to get primary namespace for package maiconpinto/cakephp-adminlte-theme

### ISSUE THREAD

**Issue by WLCD** [maiconpinto/cakephp-adminlte-theme#3]
Hello,

When I try to install I get this :+1: 

`Using version ^1.0 for maiconpinto/cakephp-adminlte-theme
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Updating maiconpinto/cakephp-adminlte-theme (dev-master 52588d9 => 1.0.0)
  Checking out f51ae20a68f6a913a1bae80203c930d4cf95055c

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Unable to get primary namespace for package maiconpinto/cakephp-adminlte-theme.
  Ensure you have added proper 'autoload' section to your plugin's config as stated in README on https://github.com/c
  akephp/plugin-installer`

**Comment by maxmasetti** [comment]
I get this too. Any solution? thx

**Comment by maiconpinto** [comment]
Hello.

Do you can update?

I installed here, and with new version of yesterday, its works now.

Let me know.

**Comment by maxmasetti** [comment]
Good, now works.

And now? some hint on how to get on?

thx
max

**Comment by maiconpinto** [comment]
Hello @maxmasetti, 

I understood a little. What hint do you say?

**Comment by maxmasetti** [comment]
hi, it is not clear how to "add" theme to new or old baked templates.
thx

**Comment by lampsbr** [comment]
Hi, 
to bake a new CRUD using a theme, in cakephp 3.x, you should use this sort of syntax: bin/cake bake all entityname --theme AdminLTE

**Comment by maiconpinto** [comment]
Exactly @lampsbr 

@maxmasetti you can run: `bin/cake bake all entityname --theme AdminLTE`.
