### ISSUE TITLE
Change the layout

### ISSUE THREAD

**Issue by mikemack** [maiconpinto/cakephp-adminlte-theme#33]
How to change the layout from default to collapse?

I try from AppController:
$this->viewBuilder()->theme('AdminLTE.collapsed');

and throw an error
An Internal Server Error Occurred

**Comment by maiconpinto** [comment]
Hello @mikemack you can change layout using https://book.cakephp.org/3.0/en/views.html#layouts 

For example: 

```php
// src/Controller/AppController.php

public function beforeRender(Event $event)
{
    $this->viewBuilder()->layout('AdminLTE.collapsed');
}
```

OR set into `.ctp` files:

```php
$this->layout = 'AdminLTE.collapsed';
```
