### ISSUE TITLE
Undefined variable: theme

### ISSUE THREAD

**Issue by wirjoadmodjo** [maiconpinto/cakephp-adminlte-theme#34]
CakePHP 3.4.x
i got this error
`Notice (8): Undefined variable: theme [ROOT\vendor\maiconpinto\cakephp-adminlte-theme\src\Template\Layout\default.ctp, line 37]`

how to solve?

thanks

**Comment by maiconpinto** [comment]
Hello @wirjoadmodjo did you configure this variable in bootstrap.php and set in AppController.php? 

Maybe help you: http://maiconpinto.github.io/cakephp-adminlte-theme/start#step15

**Comment by wirjoadmodjo** [comment]
thanks for your response.
i have configure it, i try with this code:

use Cake\Core\Configure;
$theme = Configure::read('Theme');

and that solve my problem, or any other way?

**Comment by maiconpinto** [comment]
Exactly it.
