### ISSUE TITLE
how to customize a layout

### ISSUE THREAD

**Issue by johnlanz** [maiconpinto/cakephp-adminlte-theme#36]
Hi,

What is best practices to customize a layout? You've already provided a customization for elements but not for layouts like default.ctp, login.ctp, register.ctp, etc

Thanks

**Comment by johnlanz** [comment]
I've created a AdminLTE/default.ctp inside my src/Template folder but still doesn't work.

**Comment by maiconpinto** [comment]
Hello, I did make a video to explain how to customize layout. It's a just simple way to customize, but can help you.

The audio is in brazilian portuguese, but if you follow video, you can do it. 

[Youtube](https://youtu.be/RIjtpwXr6dg)

**Comment by lightbyte** [comment]
Thanks for the video!
