### ISSUE TITLE
Prefix and elements

### ISSUE THREAD

**Issue by tomdoo** [maiconpinto/cakephp-adminlte-theme#38]
Hi,
I've created a prefix named "admin". The theme is installed and works fine.
There is only one problem when I override the element files : they are not loaded and I still have the default ones. Here's an example for footer.ctp :

| - Template
| --Admin
| --- Element
| ---- footer.ctp (doesn't work)
| -- Element
| --- footer.ctp (works fine)

AdminLTE is installed for my admin interface so I would like to store all overrides into "Admin/Elements" folder. I cannot store it directly into "Elements" because I'll have a different footer.ctp for the frontend.

**Comment by maiconpinto** [comment]
Now it's possible in release 1.0.6. See this video for solution https://www.youtube.com/watch?v=lrJw8YhrcKI
