### ISSUE TITLE
Previous and First pagination buttons marked as Active

### ISSUE THREAD

**Issue by lightbyte** [maiconpinto/cakephp-adminlte-theme#44]
CakePHP Paginator Helper creates the Previous and the Numbers with **class="active"** automatically.
When it's loaded the third page (for example), the number "3" will be active with blue color, but the first one will be active too.

I changed the line 94 in the default.ctp layout and it solve the problem:

I added this:
`&& !a.parent().parent().hasClass('pagination')`

so it looks like this:
```
93. var a = $('a[href="<?php echo $this->request->webroot . $this->request->url ?>"]');
94. if (!a.parent().hasClass('treeview') && !a.parent().parent().hasClass('pagination')) {
95.     a.parent().addClass('active').parents('.treeview').addClass('active');
96. }
```

What I have to do to apply this changes in the branch?

**Comment by maiconpinto** [comment]
Hello @lightbyte you can fork and send PR (Pull Request). I appreciate your help.

**Comment by maiconpinto** [comment]
Tks for your help. :+1:
