### ISSUE TITLE
for select option 'mulitple'='multiple' missing after baking for mapped table in cakephp

### ISSUE THREAD

**Issue by ashishonmobile** [maiconpinto/cakephp-adminlte-theme#50]
I upgraded to v1.0.6 and was trying to bake , but after baking i was not able have a select option with multiple option true. please check and let me know if this could be fix in next version.

**Comment by maiconpinto** [comment]
What is your tables and columns?

**Comment by ashishonmobile** [comment]
We have 3 table 

1) users
2) menus
3) menus_users

so when you bake users template we do have filed called 'menus' in side /users/add page. 

for v1.0.6 'menus' field have drop down but for v1.0.5 we are able to select multiple menus. I guess this is due to FormHelper changes in latest version.

Thanks,
Ashish

**Comment by maiconpinto** [comment]
@ashishonmobile this error is happening when you set the new AdminLTEView class and integrate with the new Form Helper. There are a issue #49 that was open with same error.

# 1.0.6
![1.0.6](https://user-images.githubusercontent.com/1476940/29645761-f5b0731a-8855-11e7-9f54-3ebc43997018.png)

# 1.0.5
![1.0.5](https://user-images.githubusercontent.com/1476940/29645808-1e65e5e2-8856-11e7-912b-049f2c7c30b7.png)

**Comment by maiconpinto** [comment]
This problem was fix on last commit. You can to update to 1.0.7 version.

**Comment by venikagarg** [comment]
Hello Maiconpinto,

I am using your plugin and I am facing same problem in Release 1.0.7

Regards,
Venika

**Comment by maiconpinto** [comment]
Hi @venikagarg 

Do you have this problem with new installation?

**Comment by ashishonmobile** [comment]
@maiconpinto I am also facing the same problem.

**Comment by maiconpinto** [comment]
Hi @ashishonmobile do you have the same problem yet?

**Comment by ashishonmobile** [comment]
Let me check it now. I will let you know if it is fixed.

**Comment by maiconpinto** [comment]
Hi @ashishonmobile I'm sorry for wait so time. Do you need help yet? I'll happy to help.
