### ISSUE TITLE
CSS&JS file not found...

### ISSUE THREAD

**Issue by over-write** [maiconpinto/cakephp-adminlte-theme#52]
I try to use on the manual.
Layout is available but css and js file is not found.
That reference "/admin_l_t_e/bootstrap/css/bootstrap.min.css"....
Create ”webroot” admin_l_t_e folder and copy their files?
Is Collect??
Or another way? ....settings or else?

**Comment by maiconpinto** [comment]
Hi @over-write do you have the same problem yet?

**Comment by victorjerlin** [comment]
I just experienced the same thing with cakephp 3.5.
You could run the following command to get it working:
$ ./bin/cake plugin assets symlink

It will create symlinks for the asset directories.

**Comment by maiconpinto** [comment]
Hi @over-write I'm sorry for wait so time. Do you need help yet? I'll happy to help.
