### ISSUE TITLE
loadHelper Problem

### ISSUE THREAD

**Issue by nima-rahbar** [maiconpinto/cakephp-adminlte-theme#53]
loadHelper isnt working.
When add to appView show error page: Helper class FormHelper could not be found. 

![image](https://user-images.githubusercontent.com/12494325/30247925-a8bc165e-9633-11e7-939f-c1930dccb001.png)

**Comment by maiconpinto** [comment]
Hi @nima-rahbar do you have the same problem yet?

**Comment by nima-rahbar** [comment]
thanks
its ok now
