### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by nos86** [maiconpinto/cakephp-adminlte-theme#55]
Hi,
first of all, my compliments for the job you have done here.

Now, what I want to ask is: Are you already working on a material design variant of this implementation?
Would be nice to have it for a nice and modern view of the template.

Thanks in advance,
Salvo

**Comment by maiconpinto** [comment]
Hi @nos86  

For sure, the material design is a great template. I did create a theme for [materializecss](https://github.com/maiconpinto/cakephp-materializecss-theme), if you want to test and contribute, I'll be thankful. 

Who knows I would can create new theme for Material Design, too. :smile:

**Comment by nos86** [comment]
Great..!
I assume it's enough to copy the project inside CakePHP root, but I think this not cover the CakePHP Form Helper. Is it right?

**Comment by maiconpinto** [comment]
You are right. It's not have FormHelper, yet. :smile:
