### ISSUE TITLE
Baking no longer working with --theme AdminLTE in 1.0.7

### ISSUE THREAD

**Issue by elSimmon** [maiconpinto/cakephp-adminlte-theme#56]
After installing and enabling the theme as directed, when i bake, for example: cake bake all users --theme AdminLTE, the generated views are no longer using the theme's bootstrap appearance. However this used to work perfectly in 1.0.6...

**Comment by toneguerra** [comment]
Você resolveu essa questão?
Tenho o mesmo problema.

**Comment by KasunWijesekara** [comment]
@elSimmon hi, any luck with the fix? like you mentioned the previous versions worked fine for me. The latest version has this issue where forms doesn't apply the default Bootstrap styles to the forms. 

@maiconpinto any method we can fix this? :)

**Comment by toneguerra** [comment]
@KasunWijesekara , 
I had this problem, I was able to configure this project: http://github.com/toneguerra/publiccontrol
It can serve as a basis for you to compare and configure.

**Comment by KasunWijesekara** [comment]
@toneguerra hey thanks! Can you tell me what exactly you did? Did you change the AppView.php file or something?

**Comment by KasunWijesekara** [comment]
Seems like you manually added the "Form-Control" class? @toneguerra

**Comment by toneguerra** [comment]
I'm using cake version 3.5.1, and AdminLte (bymaiconpinto) 1.0.7
I not alter manually 'Form-Control', create template using: cake bake template XXXXX --theme AdminLTE


In Bootstrap.php
---------------------------------------------------------------------------
Plugin::load('AdminLTE', ['bootstrap' => true, 'routes' => true]);

Configure::write('Theme', [
    'title' => 'AdminLTE',
    'logo' => [
        'mini' => '<b>A</b>LT',
        'large' => '<b>Admin</b>LTE'
    ],
    'login' => [
        'show_remember' => false,
        'show_register' => false,
        'show_social' => false
    ],
    'folder' => ROOT,
    'skin' => 'blue' // default is 'blue'
]);


In AppController.php
-----------------------------------------------------------------------------
    public function beforeRender(Event $event)
    {
        //Other codes

        $this->viewBuilder()->setTheme('AdminLTE');
        $this->viewBuilder()->setLayout('adminlte'); //This line just if alter layout

        $this->viewBuilder()->setClassName('AdminLTE.AdminLTE');
    }

**Comment by KasunWijesekara** [comment]
@toneguerra Thank you! You're files saved a ton of time for me 👍

**Comment by maiconpinto** [comment]
Hi @elSimmon I'm sorry for wait so time. Do you need help yet? I'll happy to help.

**Comment by elSimmon** [comment]
No, I have ported to Laravel, I'm not working on CakePhp

Simon Sesugh Lankwagh (Web Designer / Developer)
Tel:+2348111461196, you can visit my website here
<http://www.simon-lankwagh.branded.me>
