### ISSUE TITLE
--theme not working

### ISSUE THREAD

**Issue by toneguerra** [maiconpinto/cakephp-adminlte-theme#57]
--theme not working

in release 1.0.7 the command cake bake all users --theme AdminLTE not running.

In 1.0.6 is ok.

Help me please.

Thanks

**Comment by toneguerra** [comment]
--theme não está funcionando?
na release 1.0.7 o comando ex:  cake bake all users --theme AdminLTE executa, mas não assume o form.
na 1.0.6 funciona normal.

Por gentileza se puder me ajudar agradeço

Grato

**Comment by maiconpinto** [comment]
Oi @toneguerra eu tenho um vídeo do release 1.0.7, você já assistiu?

https://youtu.be/RIjtpwXr6dg

Tem algumas atualizações, do CakePHP mesmo, que não haviam na época, mas se seguir passo-a-passo e não conseguir fazer funcionar, me avise que posso fazer outro vídeo explicando como faz.

**Comment by toneguerra** [comment]
Bom dia @maiconpinto .

Vi o vídeo, e consigo alterar/configurar o layout, mas o meu problema é quando utilizo por exemplo:
cake bake all users --theme AdminLTE  , a view não é criada utilizando o form do template AdminLTE, ficando todo desconfigurado.

Obrigado pelo retorno, se puder me ajudar agradeço

**Comment by maiconpinto** [comment]
@toneguerra vou testar ainda hoje isso, e se precisar já faço a correção, daí te aviso.

**Comment by toneguerra** [comment]
Boa tarde @maiconpinto, não consegui ainda... Seu teste deu certo?
Agradeço,
Abraço

**Comment by maiconpinto** [comment]
@toneguerra boa noite. Cara acabei de conseguir testar, e está funcionando o bake all users --theme AdminLTE.

Tu consegue mandar teu projeto pra eu dar uma olhada?

**Comment by maiconpinto** [comment]
Oi @toneguerra me desculpe pela demora, você precisa de mais alguma ajuda?
