### ISSUE TITLE
How can I show the flash messages?

### ISSUE THREAD

**Issue by lampsbr** [maiconpinto/cakephp-adminlte-theme#6]
Hi,

I'm trying the theme. good job!
I noticed that cakephp's flash messages aren't being displayed by default. Is there any simple workaround to this behavior?

**Comment by maiconpinto** [comment]
Hello, you can update now, something else let me know.

![screenshot-2016-05-19 00-34-22](https://cloud.githubusercontent.com/assets/1476940/15381938/b184beb0-1d5a-11e6-9105-be51c8326d21.png)

**Comment by lampsbr** [comment]
Valeu maicon!
