### ISSUE TITLE
Configuration Not Clear 

### ISSUE THREAD

**Issue by zakblacki** [maiconpinto/cakephp-adminlte-theme#67]
I don't understand How To Modiy the layout 
I removed The Folder 
C:\xampp\htdocs\app\vendor\maiconpinto\cakephp-adminlte-theme
And Copy everything included to C:\xampp\htdocs\app\
But It Still calling for that folder vendor\maiconpinto\cakephp-adminlte-theme
I commented thoses line but still the same 
// $this->viewBuilder()->setTheme('AdminLTE');
// $this->viewBuilder()->setClassName('AdminLTE.AdminLTE');
// $this->loadHelper('Form', ['className' => 'AdminLTE.Form']);

**Comment by maiconpinto** [comment]
You can to modify layout using this video: [CakePHP AdminLTE Theme - Customize Layout](https://www.youtube.com/watch?v=RIjtpwXr6dg&lc=z22du5tq0ozdzzgszacdp43bvmblctxleqb0pquo40pw03c010c&pbjreload=10)

Basically, you need to copy vendor/maiconpinto/cakephp-adminlte-theme/src/Template/Layout/default.ctp file to your src/Template/Layout/default.ctp or adminlte.ctp if you preferer.

**Comment by maiconpinto** [comment]
Hi @zakblacki  I'm sorry for wait so time. Do you need help yet? I'll happy to help.
