### ISSUE TITLE
What is the best practice to customize layout and elements?

### ISSUE THREAD

**Issue by sspecht** [maiconpinto/cakephp-adminlte-theme#7]
Great work. The install worked as promised, but I don't know how to customize the layout.

I copied the default.ctp-layout and all of the elements from the plugin folder to the corresponding folders of my app. The changes to the template work as expected. However, when I change my copy of an element, nothing happens and the element from the plugin (with the same name) is rendered.

What is the "proper" way to customize layout, elements and content?

**Comment by maiconpinto** [comment]
Hi @sspecht 

You can update?

In this latest update, I implemented this part. 

You can test and let me know?

Thks

**Comment by maiconpinto** [comment]
Thanks @sspecht for your contribution. I implemented some customization. You can test, and something I help you.
