### ISSUE TITLE
Install assistance

### ISSUE THREAD

**Issue by asiweb** [maiconpinto/cakephp-adminlte-theme#70]
Anyone have experience installing into cakephp 1.3?
I don't understand composer.... it is asking to choose the command-line PHP I want to use. I don't know what or where this is.
![prtscr capture_2](https://user-images.githubusercontent.com/42244794/49597626-af9fcf80-f931-11e8-9eae-5bd4c119c006.jpg)

Is there a step-by-step, manual install process?
Sorry, I'm a newb.

**Comment by maiconpinto** [comment]
Hello @asiweb 

Do I can help you yet?

This theme was made to CakePHP 3 version. If you use 1.3 version, we can try to help you otherwise.
