### ISSUE TITLE
Deprecation Message

### ISSUE THREAD

**Issue by lrnzfrr** [maiconpinto/cakephp-adminlte-theme#72]
Cake 3.7 , in debug kit deprecation panel :
AdminLTE/src/View/Helper/FormHelper.php:94 
FormHelper::input() is deprecated. Use FormHelper::control() instead

**Comment by maiconpinto** [comment]
Hi @lorenzoshake Thanks for your observation. I will test it, and update in new release.

**Comment by dcoturel** [comment]
Hi guys,
I haven't seen this bug before, I'm sorry. But got to the same error in a project so I created a pull request with a proposed solution.
It is PR # 86.

**Comment by maiconpinto** [comment]
This was merged on PR #86.

Will available able in next release.
