### ISSUE TITLE
Unable to Override the templates

### ISSUE THREAD

**Issue by phronesis** [maiconpinto/cakephp-adminlte-theme#73]
For some reason, overriding the theme as stated in the documentation is not working: Cake 3.7.4. For example, to override the nav-top, I copied it over to src/Template/Plugin/AdminLTE/Element/nav-top.ctp and modified the file there, but it didn't work.

**Comment by pereiratiaggo** [comment]
try adding the following lines to the appController

`// src/Controller/AppController.php
use Cake\Core\Configure;

public function beforeRender(Event $event)
{
    // Overwrite AppView class
    $this->viewBuilder()->setClassName('AdminLTE.AdminLTE');
}`

worked here

source: https://github.com/maiconpinto/cakephp-adminlte-theme/wiki/Customize-Layout

**Comment by maiconpinto** [comment]
Thank you @pereiratiaggo for your answer. 

@phronesis let me know if you need more help.
