### ISSUE TITLE
Top Navigation

### ISSUE THREAD

**Issue by veera1908** [maiconpinto/cakephp-adminlte-theme#74]
how to change layout top navigation?

**Comment by maiconpinto** [comment]
Hi @veera1908 you can follow steps to [Customize Layout](https://github.com/maiconpinto/cakephp-adminlte-theme/wiki/Customize-Layout).

Let me know if you need more help.

**Comment by veera1908** [comment]
thank you for reply.. now top navigation layout working..

**Comment by maiconpinto** [comment]
That It's great. I am at your disposal.
