### ISSUE TITLE
unable to add images in header logo

### ISSUE THREAD

**Issue by veera1908** [maiconpinto/cakephp-adminlte-theme#77]
unable add logo image in header bootstrap.php

Configure::write('Theme', [
		'title' => 'Demo App',
		'logo' => [
			'mini' => '<b>D</b>A',
			'large' => 'i want add logo image here is it possible'
		],
		'login' => [
            'show_remember' => false,
            'show_register' => false,
            'show_social' 	=> false
        ],
		'skin' => 'green'
	]);

**Comment by maiconpinto** [comment]
Hi @veera1908 

You can add any HTML code. 

In file: Layout/default.ctp

```php
<span class="logo-lg"><?php echo Configure::read('Theme.logo.large'); ?></span>
```

So, if you configure:

```php
Configure::write('Theme', [
'title' => 'Demo App',
'logo' => [
'mini' => 'DA',
'large' => '<img src="/url/to/logo.png" />'
],
'login' => [
'show_remember' => false,
'show_register' => false,
'show_social' => false
],
'skin' => 'green'
]);
```

The code above, should works.
