### ISSUE TITLE
Url Mismatch Issue

### ISSUE THREAD

**Issue by pawan-singleinterface** [maiconpinto/cakephp-adminlte-theme#79]
URL mismatch in POST data (expected '/companies/add?url=companies/add' but found '/companies/add?url=companies/add&url=companies/add')

Step to reproduce:
Cakephp Version 3.7

1. Install Theme and configure
2. enable Security Component
3. Try to submit add form

When I disable Security Component, its working fine

Moreover, I tried without theme and follow rest of steps, it's working fine. Please help me in this regard.

**Comment by maiconpinto** [comment]
Hi @pawan-singleinterface I am testing in this link but I'm not sure that if I replicated the same issue. 

Let me know if you solved (and how to solved) this issue?

Thanks, and I'm sorry for long long time to answer you.

**Comment by pawan-singleinterface** [comment]
This is resolved. I will complete detail how I solve this. However, right now every thing is fine
