### ISSUE TITLE
Form help should use select for 'belongsToMany' inputs like tags._ids

### ISSUE THREAD

**Issue by rochamarcelo** [maiconpinto/cakephp-adminlte-theme#80]
https://github.com/maiconpinto/cakephp-adminlte-theme/blob/4b8d7cd4ab895751176704f16443f4ace87b1fed/src/View/Helper/FormHelper.php#L78

**Comment by maiconpinto** [comment]
Testing in [link](http://maiconpinto.com.br/cakephp380/users/)
